---
language: bash

branches:
  only:
    - master

env:
  global:
    - TESTRUNNER="/tmp/testrunner"
    - SHUNIT_HOME="/tmp/shunit2-2.1.7"
    - SHUNIT_COLOR="always"
    - TEST_CACHE="/tmp/test-cache"
    - HATCHET_DEPLOY_STRATEGY="git"
    - HATCHET_RETRIES="3"
    - HATCHET_APP_PREFIX="hatchet-buildpack-wildfly-${TRAVIS_JOB_ID}-"
    - secure: "M8aCFohSVntyMDjAUlLcEeWeH5SCbiQq3peKfLDrzbY9Ljpm2IK8kwH0/aEGTwVWvyagifm1xiVxt7LDzmmfrAixn8dI/aC14NWH24zfwfvzEDalQ+vhQFbM9TsAMUOywnHylzcNy11iyr/QHSdt4rmyajSwNbaGIGJFPZ4aWSfqL1VjKZiNGyqMcTzzCzv/8FkQ6W8vumn9ZkBslzhd0MQvyey3SQMvlnGwMgNGC0g9TEX+wvuUWo3dtCxWyirMEfugGpMy8QG/ItSjupTRElm2gU/vMoIBLtgZj1SmkJnYTu4TIBZOYLnyovuxNjYSPCD1KpZxwghd9FsHksPTjQDlOYbjOMO1KpLfmUJVyQhdYxOQ3Ij3/iz1q2TwaQIyBvtN2Gqa55DaDWvCT0n/UWHsEltAbx7ik5Xym1zKytR3CGfKB9CluljWeG0YO3Lmk/Lk0JLJGja2XO9wkOU7lzduN/afx9qAvfz2A5UMzrr6qJNesREk1e1kA8e3+WMJylR6H/njFj8+vfLSc9WyJBRUtb0o0ZjOqAmIZGb+DfkHAMnb2SzZA0IDLvUkYNyAaE/dcrJrvKr9bd35OpjS3LJeWSu48TD+pir4ZKMisTdDASIFIkc3ojHzBMroG8q0g+jlf1X62n7nKGbR4wY8ePJ8tZp5a0HeT9UBPvwZnlI="
    - secure: "aaUCj37X3ZrWHaMl7UmrX60Wr9UtZLE5C+TuI6l7A3m/UVw84GSRgBDfV1dU7yHN3FFEf91RMnqLrOgPAGJaQIk/bcwtWdTqTW/3er8m+pJvuLNnK4LHA68Tn876RLea52HxRjoxvD3/V24ULaQRihWH6udBHbX7zlVcoopKQ2PohoKQM2lgCEqK41LJgNQl0rrPA4Mq0lF8NH2hjm/bJXrp0k9yo0PdnNZZGY7u4a+ytwtwvx3E0iOeA6hZiKK1DZ6bcD+4P8SL6trfR29rcxgHeSRAYSBa06nTha7qs2Ue3kyj4G74FmC93irWWcCHprZnKsa9/niVDAxaYneXqSrUMX4gldNn/Sv6S+Cp/zNcgSMjHpJzmRASj+xuEpfSksrwxg3JY+ABV3CnEWd3qO902RAxtELu8Nk3qmm/r3p9qSi3x4io0Dq2hA/Ex58nVk3o81V4dPMEumEEsoZrjXx3i8fk48aAmCvj1Jp6pXH3pTx9bW/WNSkQ/3xdh7iG8R4V4jrjdiERw2mPF1vX9mh2Uf5XTxlLnHvsXtYAvC5d26DnTc48kIWY8CyLxPg9JJjssHXOoctx0S9odBc1mvFfGbEtzL1dEu6rVeUEZm/Yj54HgaDx7moWYwL3pP+wgWfj6tdeHyVoFrASMTpUANEtjFYLRgR7E8py5PhpFuw="

cache:
  directories:
    - ${TEST_CACHE}
    - /tmp/jvm-common

before_install:
  - gem update --system
  - gem install bundler --version=2.0.2

install:
  - bash etc/ci-setup.sh
  - bundle install

before_script:
  - bash etc/shellcheck.sh bin/ etc/ lib/ test/
  - bundle exec hatchet ci:setup

script:
  - ${TESTRUNNER}/bin/run -c .
  - bundle exec parallel_rspec -n 5 spec/
  - bundle exec hatchet destroy --all

after_script: test -n "${HEROKU_API_KEY}" && heroku keys:remove "$USER@$(hostname)"
