---
language: bash

branches:
  only:
    - master

env:
  global:
    - TESTRUNNER="/tmp/testrunner"
    - SHUNIT_HOME="/tmp/shunit2-2.1.7"

install: bash etc/ci-setup.sh

before_script: bash etc/shellcheck.sh

script: ${TESTRUNNER}/bin/run -c .

after_script: test -n "${HEROKU_API_KEY}" && heroku keys:remove "$USER@$(hostname)"
