[buildpack]
name = "Heroku WildFly Buildpack"

    [publish.Ignore]
    files = [
        ".gitignore",
        ".rspec",
        ".travis.yml",
        "etc/",
        "spec/",
        "test/",
        "Gemfile",
        "Gemfile.lock",
        "hatchet.json",
        "hatchet.lock"
    ]
